-- MySQL Script generated by MySQL Workbench
-- Thu Jan 30 11:49:39 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema database_desafio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema database_desafio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `database_desafio` DEFAULT CHARACTER SET utf8 ;
USE `database_desafio` ;

-- -----------------------------------------------------
-- Table `database_desafio`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_desafio`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `idade` CHAR(3) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
